### ISSUE TITLE
Warn about potential specification change

### ISSUE THREAD

**Issue by martinfleis** [wcjochem/sfarrow#1]
I am happy to see this!

One note. In GeoPandas we have a [warning about the metadata specification](https://github.com/geopandas/geopandas/blob/9fdeb1474185c8d2edaede428f57d258810d87b7/geopandas/io/arrow.py#L191). It is more than likely that geo-arrow specification 1.0 will look differently (as per discussion here https://github.com/geopandas/geo-arrow-spec) and it may be a wise thing to warn users about it. This initial implementation will not be compatible with the final one, so users should be very cautious now.

**Comment by wcjochem** [comment]
Thanks! Yes, good idea. I haven't been involved but I am tracking those discussions. I can add a warning.
